---
title: "Sentiment Plots"
author: "Julia Lueck-Benz"
date: "9/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(data.table)
library(quanteda)
library(quanteda.textstats)
library(syuzhet)
library(dplyr)
library(topicmodels)

Sys.setlocale("LC_ALL", 'en_GB.UTF-8')

triell_large <- read.csv("data/triell_2021-09-16_large.csv")

triell_large$text <-  gsub("https\\S*", "", triell_large$text)
triell_large$text <-  gsub("@\\S*", "", triell_large$text) 
triell_large$text <-  gsub("amp", "", triell_large$text) 
triell_large$text <-  gsub("[\r\n]", "", triell_large$text)
triell_large$text <-  gsub("[[:punct:]]", "", triell_large$text) # remove punctuation
```

## Add candidate identifiers

```{r candidate_id}
# Add identifier variable for appearance of candidates in tweets
triell_large <- triell_large %>%
  mutate(baerbock = ifelse(grepl("aerbock", text), 1, 0)) %>%
  mutate(laschet = ifelse(grepl("aschet", text), 10, 0)) %>%
  mutate(scholz = ifelse(grepl("olz", text), 100, 0))

# Combine id variables for all three candidates
triell_large <- triell_large %>%
  mutate(candidate_comb = baerbock + laschet + scholz)

# define labels to combination of appearance of candidates
triell_large$candidate_comb <- factor(triell_large$candidate_comb,
levels = c(1, 10, 100, 11, 101, 110, 111),
labels = c("Baerbock", "Laschet", "Scholz", "Baerbock + Laschet", "Baerbock + Scholz", "Laschet + Scholz", "Baerbock + Scholz + Laschet"))

### use only tweets during the Triell at RTL 

triell_large$month <- substr(triell_large$created_at, 1, 7)

triell_large$day <- substr(triell_large$created_at, 1, 10)

triell_large$time <- substr(triell_large$created_at, 12, 16)
                     
triellARD <- subset(triell_large, triell_large$day == "2021-09-12")

triellARDlive <- subset(triellARD, triellARD$time > "20:14")

ARDtriell <- subset(triellARDlive, triellARDlive$time < "21:55")

```


***Sentiment Analysis*** 


```{r}

method <- "nrc"
lang <- "german"
ARDtriell$sentiment <- get_sentiment(ARDtriell$text, method=method, language=lang)
ARDtriell$sentiment[1:10]

```


# Plotting sentiments 

```{r}
ggplot(data = ARDtriell, aes(x= time, y= sentiment)) + geom_point() +
  stat_summary(aes(y = sentiment,group=1), fun.y=mean, colour="red", geom="line",group=1)
```


Line chart

```{r}
ARD <- ARDtriell %>%
  filter(candidate_comb %in% c("Baerbock", "Laschet", "Scholz"))
  
ARD %>%
 ggplot(aes(x= time, y= sentiment,  group=candidate_comb ,color=candidate_comb)) +
    geom_line() + theme(legend.position="bottom") + labs(title = "Sentiments in Twitter Debate During ARD Triell", color='Candidates') + scale_color_manual(values = c("green", "black", "red")) + theme(axis.text.x = element_text(size = 3, angle = 90), text = element_text(size=10))

```

```{r}
ARD_b <- ARDtriell %>%
  filter(candidate_comb %in% c("Baerbock"))
  
ARD_b %>%
 ggplot(aes(x= time, y= sentiment,  group=candidate_comb ,color=candidate_comb)) +
    geom_line()
```


```{r}
ARD_l <- ARDtriell %>%
  filter(candidate_comb %in% c("Laschet"))
  
ARD_l %>%
 ggplot(aes(x= time, y= sentiment,  group=candidate_comb ,color=candidate_comb)) +
    geom_line()
```


```{r}
ARD_s <- ARDtriell %>%
  filter(candidate_comb %in% c("Scholz"))
  
ARD_s %>%
 ggplot(aes(x= time, y= sentiment,  group=candidate_comb ,color=candidate_comb)) +
    geom_line()
```
